package memgame.hemant.com.memorygame.repositories;

import com.j256.ormlite.field.DatabaseField;

import memgame.hemant.com.memorygame.businesslayer.INotifyObject;

/**
 *
 * Class contains model for ORMLite database.
 *
 * CRUD operations.
 *
 * Created by Hemant on 10/6/15.
 */
public class UserScoreData implements INotifyObject {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;

    @DatabaseField(uniqueIndex = true)
    String name;

    @DatabaseField(index = true)
    int score;


    UserScoreData() {

    }

    public UserScoreData(String name, int score) {
        this.name =  name;
        this.score = score;
    }


    public String getName() {
        return name;
    }

    public int getScore() {
        return score;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return name+" -> "+String.valueOf(score);
    }

}
